# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#context-availability
name: publish-a-release
description: |2
  Publish a tag on a specified branch.
author: Kohirens
inputs: # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#inputs-context
    github_token_var:
        default: GH_TOKEN
        description: Name of the environment variable holding the GitHub API token.
        required: true
    main_trunk_branch:
        default: "main"
        description: Name of the main trunk branch to tag.
        required: true
    repository:
        default: ${{ github.repository }}
        description: GitHub owner/repository to check; they are together since that is how GA provides them.
        required: false
    tag_cmd:
        default: ""
        description: Command to run to get the semantic version tag, will override the auto generated value.
        required: false
    tag_env_var:
        default: ""
        description: Environment variable to get the semantic version tag, will override the auto generated value.
        required: false
    tag_file:
        default: ""
        description: File to get the semantic version tag, will override the auto generated value.
        required: false
    verbosity_level:
        default: "6"
        description: Set the logging verbosity level, a value between 1-6, 1 being the least and 6 being the most.
        required: false
    working_directory:
        default: ${{ github.workspace }}
        description: In case you need to customize, defaults to the current dir.
        required: true

outputs:
    tag:
        description: A value of yes indicates a tag has already been published on GitHub
        value: ${{ steps.gh_has_release.outputs.tag }}

runs: # https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
    using: docker
    image: docker://kohirens/version-release:dev
    env:
      PARAM_OWNER_SLASH_REPO: ${{ inputs.repository }}
      PARAM_TAG_CMD: ${{ inputs.tag_cmd }}
      PARAM_TAG_ENV_VAR: ${{ inputs.tag_env_var }}
      PARAM_TAG_FILE: ${{ inputs.tag_file }}
      PARAM_MAIN_TRUNK_BRANCH: ${{ inputs.main_trunk_branch }}
      PARAM_WORKING_DIRECTORY: ${{ inputs.working_directory }}
      VERBOSITY_LEVEL: ${{ inputs.verbosity_level }}
    pre-entrypoint: gh-has-release.sh
    entrypoint: tag-and-release.sh
#    steps: # https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsstepsuses
#        - name: Check release does not exist
#          id: "gh_has_release"
#          entrypoint: gh-has-release.sh
#          env:
#              PARAM_FILE: ${{ inputs.release_file }}
#              PARAM_OWNER_SLASH_REPO: ${{ inputs.repo }}
#              PARAM_TAG_CMD: ${{ inputs.tag_cmd }}
#              PARAM_TAG_ENV_VAR: ${{ inputs.tag_env_var }}
#              PARAM_TAG_FILE: ${{ inputs.tag_file }}
#              VERBOSITY_LEVEL: ${{ inputs.verbosity_level }}
#        - if: ${{ !failure() }}
#          uses: docker://kohirens/version-release:dev
#          id: "tag_and_release"
#          entrypoint: tag-and-release.sh
#          env: # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
#            PARAM_MAIN_TRUNK_BRANCH: ${{ inputs.main_trunk_branch }}
#            PARAM_TAG_CMD: ${{ inputs.tag_cmd }}
#            PARAM_TAG_ENV_VAR: ${{ inputs.tag_env_var }}
#            PARAM_TAG_FILE: ${{ inputs.tag_file }}
#            PARAM_WORKING_DIRECTORY: ${{ inputs.working_directory }}
#            VERBOSITY_LEVEL: ${{ inputs.verbosity_level }}
