version: 2.1

setup: true

orbs:
  # For CircleCI Server, some Orbs like `orb-tools` will need the correct URL of the server.
  # You can set the project environment variable CIRCLECI_CLI_HOST="https://circleci.server.domain", for example,
  # so that it is available for all jobs. You should also set CIRCLECI_CLI_TOKEN for authentication.
  vro: << pipeline.parameters.orb_repo >>@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@11.2.0
  bats: circleci/bats@1.0.0
  shellcheck: circleci/shellcheck@3.1.1
  cli: circleci/circleci-cli@0.1.9

# Pipeline Parameters
# also see: https://circleci.com/docs/2.0/pipeline-variables/
parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
  ssh-finger:
    description: SSH fingerprint.
    type: string
    default: "0a:16:aa:bf:a7:8b:2a:68:aa:62:28:63:20:11:62:4a"
  orb_repo:
    description: Orb repository
    type: string
    default: "kohirens/version-release"
  auth_context:
    description: "Context containing keys for auth."
    type: string
    default: "kohirens-orb-publishing"

jobs:
  orb-publish:
    executor: cli/default
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: "Publish Orb"
          command: |
            GIT_TAG=$(git tag --points-at HEAD)
            if [ -z "${GIT_TAG}" ]; then
              echo "no tag found in order to publish Orb"
              exit 1
            fi
            circleci orb --skip-update-check validate orb.yml
            circleci orb publish --skip-update-check orb.yml << pipeline.parameters.orb_repo >>@${GIT_TAG} --token ${CIRCLE_TOKEN}
  debug-info:
    executor: vro/default
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: "Debug info"
          command: |
            wd=$(pwd)
            who=$(whoami)
            printf "current directory: %s\n" "${wd}"
            printf "current user: %s\n" "${who}"
            echo "list current directory contents:"
            ls -la .

branches-to-skip: &branches-to-skip
  branches:
    ignore: /main|updated-changelog-skip-ci|auto-update-changelog/

workflows:
  test-pack:
    jobs:
      - orb-tools/continue: # load the deploy.yml
          filters:
            branches:
              only: main
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          config-path: "deploy.yml"
      - orb-tools/lint:
          filters: *branches-to-skip
      - orb-tools/pack:
          filters: *branches-to-skip
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
          filters: *branches-to-skip
      - bats/run:
          path: ./src/tests
          filters: *branches-to-skip
      - orb-tools/publish:
          name: "publish-dev"
          orb-name: << pipeline.parameters.orb_repo >>
          context: << pipeline.parameters.auth_context >>
          github-token: "GH_TOKEN"
          vcs-type: << pipeline.project.type >>
          requires: [ orb-tools/lint, orb-tools/pack, bats/run, shellcheck/check ]
          filters: *branches-to-skip
      # Trigger integration test on dev:${CIRCLE_SHA1:0:7} of your orb
      - orb-tools/continue:
          filters: *branches-to-skip
          pipeline-number: << pipeline.number >>
          requires: [ publish-dev ]
          vcs-type: << pipeline.project.type >>
      - debug-info:
          filters: *branches-to-skip
          requires: [ orb-tools/pack ]
