version: 2.1

orbs:
  # Chicken-Egg/Catch-22 scenario
  # So when the "test-pack" pipeline runs "dev-orb-version" will be "dev:alpha", the previous build.
  # Only after a successful run of "test-pack" does a new version of your orb exist with the latest features.
  # This means you cannot use new features in the integration test pipeline until afterward. Make the process as follows:
  # 1. Push out new features/breaking changes without updating the integration pipeline.
  # 2. Make sure the pipeline succeeds.
  # 3. Update your integration pipeline to test the new features/breaking changes.
  # Further: When the "integration-test_deploy" pipeline runs it will use the latest dev image set to the latest hash.
  # However, the whole CI config is compiled before building your latest dev orb (with its latest features). So any
  # calls to those features will throw errors and the pipeline will fail.
  version-release: kohirens/version-release@<<pipeline.parameters.dev-orb-version>> # We are calling our orb before we build the latest dev version!
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-1:
    docker:
      - image: kohirens/git-tool-belt:0.3.0
        auth:
          username: ${DH_USER}
          password: ${DH_PASS}
    steps:
      - checkout
      # Push new changes first, before adding new tests to your config.
      - run: echo "<<pipeline.parameters.dev-orb-version>>"
      - version-release/git-chglog-update:
          configFile: "src/tests/data/.chglog/config.yml"
          outputFile: "CHANGELOG-4000.md"

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
      # optional: Run BATS tests against your scripts
      - bats/run:
          path: ./src/tests
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: kohirens/version-release
          context: orb-publishing # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Run any integration tests defined within the `jobs` key.
      - integration-test-1
      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      # uses CircleCI Kohirens SSH key/fingerprint
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: kohirens/version-release
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: ${SSH_FINGER}
          requires:
            - integration-test-1
          filters:
            branches:
              only:
                - main
