version: 2.1

setup: true

orbs:
  vro: << pipeline.parameters.orb_repo >>@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@11.2.0
  bats: circleci/bats@1.0.0
  shellcheck: circleci/shellcheck@3.1.1
  cli: circleci/circleci-cli@0.1.9
  continuation: circleci/continuation@0.3.1

# Pipeline Parameters
# also see: https://circleci.com/docs/2.0/pipeline-variables/
parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
  ssh-finger:
    description: SSH fingerprint.
    type: string
    default: "0a:16:aa:bf:a7:8b:2a:68:aa:62:28:63:20:11:62:4a"
  orb_repo:
    description: Orb repository
    type: string
    default: "kohirens/version-release"
  auth_context:
    description: "Context containing keys for auth."
    type: string
    default: "kohirens-orb-publishing"
  changelog_path:
    description: "Path to the changelog file."
    type: string
    default: "CHANGELOG.md"

jobs:
  debug-info:
    executor: vro/default
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: "Debug info"
          command: |
            wd=$(pwd)
            who=$(whoami)
            printf "current directory: %s\n" "${wd}"
            printf "current user: %s\n" "${who}"
            echo "list current directory contents:"
            ls -la .
  choose-a-workflow:
    executor: vro/default
    steps:
      - checkout
      - attach_workspace: { at: '.' }
      - vro/generate-a-workflow
      - continuation/continue:
          circleci_domain: "circleci.com"
          configuration_path: ".circleci/generated-config.yml"
          parameters: ".circleci/generated-parameters.json"

branches-to-skip: &branches-to-skip
  branches:
    ignore: /main|updated-changelog-skip-ci|auto-update-changelog/

workflows:
  workflow-picker:
    jobs:
      - orb-tools/lint:
          filters: *branches-to-skip
      - orb-tools/pack:
          filters: *branches-to-skip
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
          filters: *branches-to-skip
      - bats/run:
          path: ./src/tests
          filters: *branches-to-skip
      - orb-tools/publish:
          name: "publish-dev"
          orb-name: << pipeline.parameters.orb_repo >>
          context: << pipeline.parameters.auth_context >>
          github-token: "GH_TOKEN"
          vcs-type: << pipeline.project.type >>
          requires: [ orb-tools/lint, orb-tools/pack, bats/run, shellcheck/check ]
          filters: *branches-to-skip
      - debug-info:
          filters: *branches-to-skip
          requires: [ orb-tools/pack ]
      - continuation/continue: # Trigger integration test on dev:${CIRCLE_SHA1:0:7} of your orb
          requires: [ publish-dev ]
          configuration_path: ".circleci/integration-tests.yml"
          circleci_domain: "circleci.com"
          parameters: '{ "continued_automation": "integration-test" }'
      - choose-a-workflow:
          filters: { branches: { only: main } }
