version: 2.1

orbs:
    bats: circleci/bats@1.0.0
    cli: circleci/circleci-cli@0.1.9
    ot: circleci/orb-tools@10.1.0
    shellcheck: circleci/shellcheck@3.1.1
    vr: kohirens/version-release@<< pipeline.parameters.orb_version >>

parameters:
    ctx_auto_release:
        default: "kohirens-automation"
        description: Release automation
        type: string
    ctx_docker_hub:
        default: "kohirens-automation-dockerhub"
        description: Container automation
        type: string
    orb_version:
        default: "dev:e56d3fe25181d4701618000b3459f053a59bf080"
        description: >
            The development version of the orb to test.
            This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
            A "dev:alpha" version must exist for the initial pipeline run.
        type: string
    orb_repo:
        default: "kohirens/version-release"
        description: Orb repository
        type: string
    run_integration_tests:
        type: boolean
        default: false
        description: Run integration tests
    ssh_finger:
        description: SSH fingerprint.
        type: string
        default: "SHA256:33aENw5b67lKO3SVfCEeGeMthT+BUKsfyj+0YyU+Qz4"
    triggered_flow:
        default: "workflow-selector"
        description: Workflow to be executed.
        type: string

executors:
    image-builder:
        docker: # see https://circleci.com/docs/building-docker-images/#docker-version
            - image: docker:20.10.18-git
              auth:
                  username: ${DH_USER}
                  password: ${DH_PASS}
        resource_class: small

filter-semantic-tag: &filter-semantic-tag
    tags:
        only: /^v?\d+\.\d+\.\d+$/
    branches:
        ignore: /.*/

main-filter: &branches-to-skip
    branches:
        ignore: /main|auto-update-changelog/

pre-attach: &pre-attach
    - attach_workspace: { at: "." }

jobs:
    co:
        executor: vr/default
        steps:
            - checkout
            - persist_to_workspace: { root: ".",  paths: [ "*" ] }

    orb-publish:
        parameters:
            ver_tag:
                default: "dev:alpha"
                description: version tag for the image
                type: string
        executor: cli/default
        steps:
            - attach_workspace: { at: "." }
            - run:
                  name: "Publish Orb"
                  command: |
                      # Update the placeholders in these files
                      sed -i -e "s/VERSION_RELEASE_IMAGE/<<parameters.ver_tag>>/g" src/executors/default.yml
                      sed -i -e "s/VERSION_RELEASE_IMAGE/<<parameters.ver_tag>>/g" src/jobs/publish-changelog.yml
                      sed -i -e "s/VERSION_RELEASE_IMAGE/<<parameters.ver_tag>>/g" src/jobs/tag-and-release.yml
                      sed -i -e "s/VERSION_RELEASE_IMAGE/<<parameters.ver_tag>>/g" src/jobs/workflow-selector.yml
                      BUILD_VER=<<parameters.ver_tag>>
                      if [ -z "${BUILD_VER}" ]; then
                        echo "no tag found in order to publish Orb"
                        exit 1
                      fi
                      circleci orb --skip-update-check pack src > orb.yml
                      circleci orb --skip-update-check validate orb.yml
                      circleci orb publish --skip-update-check orb.yml << pipeline.parameters.orb_repo >>@${BUILD_VER} --token ${CIRCLE_TOKEN}

    integration-test-vr:
        executor: image-builder
        environment:
            DOCKER_BUILDKIT: 1
        steps:
            - attach_workspace: { at: "." }
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: "Build mock server tests environment"
                  command: |
                      docker build --rm -f .docker/mock-server/Dockerfile -t mock-server --progress plain .
            - run:
                  name: "Run tests against mock server environment"
                  command: |
                      docker run -it \
                          --rm \
                          --add-host "api.circleci.com:127.0.0.1" \
                          --add-host "app.circleci.com:127.0.0.1" \
                          --add-host "github.com:127.0.0.1" \
                          --add-host "api.github.com:127.0.0.1" \
                          --env-file .docker/mock-server/integration-test.env \
                          mock-server

workflows:
    quality-checks:
        jobs:
            - co:
                  filters: *branches-to-skip
            - bats/run:
                  pre-steps: *pre-attach
                  requires: [ co ]
                  path: ./src/tests
            - shellcheck/check:
                  pre-steps: *pre-attach
                  requires: [ co ]
                  dir: ./src/scripts
                  exclude: SC2148
            - orb-publish:
                  name: "publish-dev-orb"
                  context: << pipeline.parameters.ctx_auto_release >>
                  requires: [ bats/run, shellcheck/check ]
                  ver_tag: "dev:<< pipeline.git.revision >>"
            - ot/trigger-integration-tests-workflow:
                  name: trigger-integration-tests
                  context: << pipeline.parameters.ctx_auto_release >>
                  pipeline-param-map: >-
                      {\"run_integration_tests\": true, \"orb_version\": \"dev:<< pipeline.git.revision >>\"}
                  requires: [ publish-dev-orb ]
        when:
            and:
                - not: << pipeline.parameters.run_integration_tests >>

    test-orb:
        jobs:
            - co
            - integration-test-vr:
                  context: <<pipeline.parameters.ctx_docker_hub>>
                  filters: *branches-to-skip
                  requires: [ co ]
            - vr/publish-docker-hub:
                  name: "publish-dev-image"
                  context: << pipeline.parameters.ctx_docker_hub >>
                  requires: [ co ]
                  dockerfile: ".docker/vr/Dockerfile"
                  image_tag: "dev"
                  repository: << pipeline.parameters.orb_repo >>
        when: << pipeline.parameters.run_integration_tests >>

    workflow-selector:
        when:
            and:
                - equal: [ "workflow-selector", << pipeline.parameters.triggered_flow >> ]
                - equal: [ main, << pipeline.git.branch >> ]
        jobs:
            - vr/workflow-selector:
                  context: << pipeline.parameters.ctx_auto_release >>
                  ssh_finger: << pipeline.parameters.ssh_finger >>
                  exec_img_tag: "dev"

    publish-changelog:
        when:
            and:
                - equal: [ "publish-changelog", << pipeline.parameters.triggered_flow >> ]
        jobs:
            - vr/publish-changelog:
                  context: << pipeline.parameters.ctx_auto_release >>
                  ssh_finger: << pipeline.parameters.ssh_finger >>
                  exec_img_tag: "dev"

    publish-release-tag:
        when:
            and:
                - equal: [ "publish-release-tag", << pipeline.parameters.triggered_flow >> ]
        jobs:
            - vr/tag-and-release:
                  context: << pipeline.parameters.ctx_auto_release >>
                  exec_img_tag: "dev"

    on-tag-release:
        jobs:
            - co:
                  filters:
                      <<: *filter-semantic-tag
            - vr/publish-docker-hub:
                  name: "publish-prod-image-semver"
                  context: << pipeline.parameters.ctx_docker_hub >>
                  requires: [ co ]
                  filters:
                      <<: *filter-semantic-tag
                  do_attach_workspace: true
                  do_checkout: false
                  dockerfile: ".docker/vr/Dockerfile"
                  repository: << pipeline.parameters.orb_repo >>
                  image_tag: "<< pipeline.git.tag >>"
            - orb-publish:
                  name: "publish-prod-orb"
                  context: << pipeline.parameters.ctx_auto_release >>
                  requires: [ publish-prod-image-semver ]
                  ver_tag: << pipeline.git.tag >>
                  filters:
                      <<: *filter-semantic-tag
