version: 2.1

orbs:
  vro: << pipeline.parameters.orb_repo >>@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
  orb_repo:
    description: Orb repository
    type: string
    default: "kohirens/version-release"
  continued_automation:
    description: Automation workflow description
    type: string
    default: ""
  repo_path_01:
    description: Path to repo
    type: string
    default: "/tmp/repo-01"

main-filter: &branches-to-skip
    branches:
      ignore: /main|updated-changelog-skip-ci|auto-update-changelog/

jobs:
  integration-test-1:
    executor: vro/default
    steps:
      - checkout
      - run:
          command: |
            repoPath="/tmp/repo-01"
            git clone -b main src/tests/data/repo-01.bundle << pipeline.parameters.repo_path_01 >>
            git status
            cp -R src/tests/data/.chglog << pipeline.parameters.repo_path_01 >>
            ls -la << pipeline.parameters.repo_path_01 >>
      - vro/git-chglog-update:
          repository_path: << pipeline.parameters.repo_path_01 >>
      - run:
          command: |
            ls -la << pipeline.parameters.repo_path_01 >>

workflows:
  test-orb:
    jobs:
      - integration-test-1:
          filters: *branches-to-skip