version: 2.1

orbs:
    vro: <<pipeline.parameters.orb_repo>>@<<pipeline.parameters.orb_version>>

parameters:
    continued_automation:
        default: ""
        description: Automation workflow description
        type: string
    ctx_docker_hub:
        default: "kohirens-automation-dockerhub"
        description: Container automation
        type: string
    orb_version:
        default: "dev:alpha"
        description: >
          The development version of the orb to test.
          This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
          A "dev:alpha" version must exist for the initial pipeline run.
        type: string
    orb_repo:
        default: "kohirens/version-release"
        description: Orb repository
        type: string
    repo_path_01:
        default: "/tmp/repo-01"
        description: Path to repo
        type: string

main-filter: &branches-to-skip
    branches:
        ignore: /main|updated-changelog-skip-ci|auto-update-changelog/

jobs:
    co:
        executor: vro/default
        steps:
            - checkout
            - persist_to_workspace: { root: ".",  paths: [ "*" ] }
    integration-test-vr:
        docker: # see https://circleci.com/docs/building-docker-images/#docker-version
            - image: docker:20.10.18-git
              auth:
                  username: ${DH_USER}
                  password: ${DH_PASS}
        environment:
            DOCKER_BUILDKIT: 1
        steps:
            - attach_workspace: { at: "." }
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                name: "Build mock server tests environment"
                command: |
                    docker build --rm -f .docker/mock-server/Dockerfile -t mock-server --progress plain .
            - run:
                name: "Run tests against mock server environment"
                command: |
                    docker run -it \
                        --rm \
                        --add-host "api.circleci.com:127.0.0.1" \
                        --add-host "app.circleci.com:127.0.0.1" \
                        --add-host "github.com:127.0.0.1" \
                        --add-host "api.github.com:127.0.0.1" \
                        --env-file .docker/mock-server/integration-test.env \
                        mock-server

workflows:
    test-orb:
        jobs:
            - co
            - integration-test-vr:
                context: <<pipeline.parameters.ctx_docker_hub>>
                filters: *branches-to-skip
                requires: [ co ]
