version: 2.1

orbs:
  # For CircleCI Server, some Orbs like `orb-tools` will need the correct URL of the server.
  # You can set the project environment variable CIRCLECI_CLI_HOST="https://circleci.server.domain", for example,
  # so that it is available for all jobs. You should also set CIRCLECI_CLI_TOKEN for authentication.
  # TODO: Change to a semantic version after release.
  vro: << pipeline.parameters.orb_repo >>@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@11.2.0
  cli: circleci/circleci-cli@0.1.8

# Pipeline Parameters
# also see: https://circleci.com/docs/2.0/pipeline-variables/
parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
  ssh-finger:
    description: SSH fingerprint.
    type: string
    default: "0a:16:aa:bf:a7:8b:2a:68:aa:62:28:63:20:11:62:4a"
  orb_repo:
    description: Orb repository
    type: string
    default: "kohirens/version-release"
  auth_context:
    description: "Context containing keys for auth."
    type: string
    default: "kohirens-orb-publishing"
  triggered_by_bot:
    description: Trigger publishing a release tag workflow.
    type: boolean
    default: false
  continued_automation:
    description: Automation workflow description
    type: string
    default: ""

workflows:
  publish-changelog:
    when:
      and:
        - equal: [ << pipeline.git.branch >>, "main" ]
        - equal: [ << pipeline.parameters.continued_automation >>, "publish-changelog" ]
    jobs:
      - vro/publish-changelog:
          name: "auto-update-changelog"
          context: << pipeline.parameters.auth_context >>
          ssh_finger: << pipeline.parameters.ssh-finger >>
          trigger_tag_and_release: false # when using a dynamic workflow this get trigger by the generate-workflow script
