version: 2.1

orbs:
  vro: kohirens/version-release@2.3.5
  orb-tools: circleci/orb-tools@12.0.3
  cli: circleci/circleci-cli@0.1.9

parameters:
  continued_automation:
    description: Automation workflow description
    type: string
    default: ""
  ctx_auto_release:
    description: "Context containing keys for auth."
    type: string
    default: "kohirens-automation"
  ssh_finger:
    description: SSH fingerprint.
    type: string
    default: "0a:16:aa:bf:a7:8b:2a:68:aa:62:28:63:20:11:62:4a"
  triggered_flow:
    default: ""
    description: Trigger workflow.
    type: string

workflows:
  publish-changelog:
    when:
      and:
        - equal: [ << pipeline.git.branch >>, "main" ]
        - equal: ["publish-changelog", << pipeline.triggered_flow >>]
    jobs:
      - vro/publish-changelog:
          name: "auto-update-changelog"
          context: << pipeline.parameters.secrets >>
          ssh_finger: << pipeline.parameters.ssh-finger >>
