version: 2.1
# This config should only be run on the main trunk branch
orbs:
  # For CircleCI Server, some Orbs like `orb-tools` will need the correct URL of the server.
  # You can set the project environment variable CIRCLECI_CLI_HOST="https://circleci.server.domain", for example,
  # so that it is available for all jobs. You should also set CIRCLECI_CLI_TOKEN for authentication.
  vro: << pipeline.parameters.orb_repo >>@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@11.2.0
  cli: circleci/circleci-cli@0.1.8

# Pipeline Parameters
# also see: https://circleci.com/docs/2.0/pipeline-variables/
parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
  ssh-finger:
    description: SSH fingerprint.
    type: string
    default: "0a:16:aa:bf:a7:8b:2a:68:aa:62:28:63:20:11:62:4a"
  orb_repo:
    description: Orb repository
    type: string
    default: "kohirens/version-release"
  auth_context:
    description: "Context containing keys for auth."
    type: string
    default: "kohirens-orb-publishing"
  continued_automation:
    description: Automation workflow description
    type: string
    default: ""

jobs:

  orb-publish:
    executor: cli/default
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: "Publish Orb"
          command: |
            GIT_TAG=$(git tag --points-at HEAD)
            if [ -z "${GIT_TAG}" ]; then
              echo "no tag found in order to publish Orb"
              exit 1
            fi
            circleci orb --skip-update-check validate orb.yml
            circleci orb publish --skip-update-check orb.yml << pipeline.parameters.orb_repo >>@${GIT_TAG} --token ${CIRCLE_TOKEN}

workflows:
  check-changelog:
    when:
      and:
        - equal: [ << pipeline.parameters.continued_automation >>, "publish-changelog" ]
    jobs:
      - vro/publish-changelog:
          name: "check-changelog"
          context: << pipeline.parameters.auth_context >>
          filters:
            branches:
              only: main
          ssh_finger: << pipeline.parameters.ssh-finger >>
  publish-a-release:
    when:
      and:
        - equal: [ << pipeline.parameters.continued_automation >>, "publish-new-tag" ]
    jobs:
      - vro/tag-and-release:
          requires: [ vro/publish-changelog ]
          context: << pipeline.parameters.auth_context >>
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          requires: [ check-changelog ]
          vcs-type: << pipeline.project.type >>
          config-path: ".circleci/publish.yml"
