version: 2.1
# This config should only be run on the main trunk branch
orbs:
  vro: kohirens/version-release@2.3.5

parameters:
  continued_automation:
    description: Automation workflow description
    type: string
    default: ""
  ctx_auto_release:
    description: "Context containing keys for auth."
    type: string
    default: "kohirens-automation"
  triggered_flow:
    default: ""
    description: Trigger workflow.
    type: string

workflows:
  publish-a-release:
    when:
      and:
        - equal: ["main", << pipeline.git.branch >>]
        - equal: ["tag-and-release", << pipeline.parameters.triggered_flow >>]
    jobs:
      - vro/tag-and-release:
          context: << pipeline.parameters.ctx_auto_release >>
