description: >
  Check for a git-chglog configuration file, and add if missing.
parameters:
  configFile:
    type: string
    default: ".chglog/config.yml"
    description: Location of a git-chglog configuration file.
steps:
  - run:
      environment:
        PARAM_CONFIGFILE: "<< parameters.configFile >>"
      name: Check for config
      command: << include(scripts/add-missing-chglog-config.sh) >>
