description: >
  version release executor with git-tool-belt.

parameters:
  exec_img_tag:
    type: string
    default: "VERSION_RELEASE_IMAGE"

docker:
  - image: kohirens/version-release:<< parameters.exec_img_tag >>
    auth:
      username: ${DH_USER}
      password: ${DH_PASS}
