# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#context-availability
name: publish-a-changelog
description:  |2
  Commit changes to the changelog and merge into a remote branch using the process:

  1. Configure Git to allow a commit.
  2. Making a new branch.
  3. Detect and commit the changes to the CHANGELOG, if none, then exit.
  4. Pushing the branch back to remote GitHub.
  5. Use the GitHub CLI to make a PR.
  6. Then immediately merge the changes in the desired branch.

  We use a PR instead of a push in case the branch is protected from direct pushes.

inputs: # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#inputs-context
    changelog_file:
        default: "CHANGELOG.md"
        description: Location to output/update the CHANGELOG file.
        required: true
    changelog_hash:
        default: ""
        description: A checksum hash of the changelog from a the selector-workflow to compare against the current changelog, if they are different there are more changes to publish.
    github_server:
        default: "github.com"
        description: GitHub server domain name.
        required: true
    github_token_var:
        default: GH_TOKEN
        description: Name of the environment variable holding the GitHub API token.
        required: true
    main_trunk_branch:
        default: "main"
        description: Name of the main trunk branch to tag.
        required: true
    merge_type:
        default: "rebase"
        description: Type of merge to perform, choose between merge|squash|rebase.
        type: enum
        enum: [ "merge", "rebase", "squash" ]
        required: true
    tag_cmd:
        default: ""
        description: Command to run to get the semantic version tag, will override the auto generated value.
        required: false
    tag_env_var:
        default: ""
        description: Environment variable to get the semantic version tag, will override the auto generated value.
        required: false
    tag_file:
        default: ""
        description: File to get the semantic version tag, will override the auto generated value.
        required: false
    verbosity_level:
        default: "6"
        description: Set the logging verbosity level, a value between 1-6, 1 being the least and 6 being the most.
        required: false
    working_directory:
        default: ${{ github.workspace }}
        description: In case you need to customize, defaults to the current dir.
        required: true

runs: # https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions
    using: docker
    image: docker://kohirens/version-release:dev
    env: # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
        PARAM_CHANGELOG_FILE: ${{ inputs.changelog_file }}
        PARAM_MAIN_TRUNK_BRANCH: ${{ inputs.main_trunk_branch }}
        PARAM_MERGE_TYPE: ${{ inputs.merge_type }}
        PARAM_GITHUB_SERVER: ${{ inputs.github_server }}
        PARAM_TAG_CMD: ${{ inputs.tag_cmd }}
        PARAM_TAG_ENV_VAR: ${{ inputs.tag_env_var }}
        PARAM_TAG_FILE: ${{ inputs.tag_file }}
        PARAM_WORKING_DIRECTORY: ${{ inputs.working_directory }}
        VERBOSITY_LEVEL: ${{ inputs.verbosity_level }}
    entrypoint: sh
    args:
        - /usr/local/bin/publish-changelog.sh
