version: '3.8'

services:
    cli:
        build:
            args:
                USER_NAME: '${USER_NAME}'
                REPO: '${REPO}'
            dockerfile: '.docker/vr/Dockerfile'
            context: '..'
            target: 'build'
        env_file:
            - 'vr/app.env'
        image: 'kohirens/version-release:dev'
        networks:
            default:

        volumes:
            - '../:/home/${USER_NAME}/src/${REPO}'
            - '~/.ssh/known_hosts:/home/${USER_NAME}/.ssh/known_hosts'
            - 'vscode:/home/${USER_NAME}/.vscode-server'

    web:
        build:
            args:
                REPO: '${REPO}'
            dockerfile: '.docker/mock-server/Dockerfile'
            context: '..'
        environment:
            DO_STAY: 1
        env_file:
            - 'mock-server/integration-test.env'
        image: 'mock-server'
        networks:
            default:
                aliases:
                    - "circleci.com"
                    - "api.circleci.com"
                    - "app.circleci.com"
                    - "github.com"
                    - "api.github.com"
        volumes:
            - '../:/root/src/${REPO}/'

volumes:
    vscode: null
