description: |2
  Update the CHANGELOG.md using only specifically formatted Git commit messages, for example:

    add: Awesome new feature
    rmv: Obsolete features
    BREAKING CHANGE

usage:
  version: 2.1
  orbs:
    vro: kohirens/version-release@0.3.5
  workflows:
    use-my-orb:
      jobs:
        - checkout
        - update-the-chglog:
            requires: [ checkout ]
jobs:
  update-the-chglog:
    executor: vro/default
    steps:
      - vro/git-chglog-update:
          configFile: ".chglog/config.yml"
          outputFile: "CHANGELOG.md"
