name: workflow-selector
run-name: ${{ github.actor }} is checking which workflow to run
on:
    workflow_call:
        inputs:
            committer_email:
                description: Git user email address to use when commiting the changelog.
                required: true
                type: string
            committer_gpg_key:
                description: Git user GPG key to use when commiting the changelog.
                default: ""
                required: false
                type: string
            committer_name:
                description: Git username to use when commiting the changelog.
                required: true
                type: string
            add_files_to_commit:
                default: ""
                description: |2
                  Name of an artifact upload containing a text file (UTF-8)
                  containing 1 file per line to add along with the changelog
                  commit. Line endings can be Linux, Mac, or Windows. The file
                  will de downloaded to the root of the GITHUB_WORKING
                  directory.should be relative to the root of the repository.
                required: false
                type: string
            add_files_to_commit_run_id:
                default: ""
                description: |2
                  The ID of the workflow run that uploaded the artifact.
                required: false
                type: string
            enable_tag_v_prefix:
                default: false
                description: |2
                  Prefix git tags with a "v" before the semantic version number.
                required: false
                type: boolean
            github_api_url:
                default: "https://api.github.com"
                description: Github API URL.
                required: false
                type: string
            github_server:
                default: "github.com"
                description: GitHub server domain name.
                required: false
                type: string
        secrets:
            github_write_token:
                required: true
                description: Personal GitHub access token to allow GitHub API request to trigger workflows.

concurrency:
    group: qa-group
    cancel-in-progress: false

env:
    GH_WRITE_TOKEN: ${{ secrets.github_write_token }}

jobs:
    select-a-workflow:
        runs-on: ubuntu-latest
        name: Select which workflow to run
        outputs:
            workflow: ${{ steps.selector.outputs.workflow }}
            changelog_hash: ${{ steps.selector.outputs.changelog_hash }}
            next_semver: ${{ steps.selector.outputs.next_semver }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-tags: true
                  fetch-depth: 0
            - name: Select a workflow
              uses: kohirens/version-release/.github/actions/workflow-selector@5.1.6
              id: selector
              with:
                  enable_tag_v_prefix: ${{ inputs.enable_tag_v_prefix }}
                  github_api_url: ${{ inputs.github_api_url }}
                  github_server: ${{ inputs.github_server }}
    publish-changelog:
        if: ${{ needs.select-a-workflow.outputs.workflow == 'publish-changelog' }}
        runs-on: ubuntu-latest
        name: Publish changelog workflow
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-tags: true
                  fetch-depth: 0
            - name: Download the additional files artifact
              uses: actions/download-artifact@v4
              if: ${{ inputs.add_files_to_commit != '' }}
              with:
                  name: ${{ inputs.add_files_to_commit }}
                  merge-multiple: true
                  run-id: ${{ inputs.add_files_to_commit_run_id }}
            - name: Update and publish the changelog
              uses: kohirens/version-release/.github/actions/publish-changelog@5.1.6
              id: changelog
              with:
                  changelog_hash: ${{ needs.select-a-workflow.outputs.changelog_hash }}
                  committer_email: ${{ inputs.committer_email }}
                  committer_gpg_key: ${{ inputs.committer_gpg_key }}
                  committer_name: ${{ inputs.committer_name }}
                  add_files_to_commit: ${{ inputs.add_files_to_commit }}
                  enable_tag_v_prefix: ${{ inputs.enable_tag_v_prefix }}
                  github_api_url: ${{ inputs.github_api_url }}
                  github_server: ${{ inputs.github_server }}
        needs: select-a-workflow
    publish-release-tag:
        if: ${{ needs.select-a-workflow.outputs.workflow == 'publish-release-tag' }}
        runs-on: ubuntu-latest
        name: Publish release workflow
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-tags: true
                  fetch-depth: 0
            - name: Publish a release
              uses: kohirens/version-release/.github/actions/publish-release-tag@5.1.6
              id: release
              with:
                  tag_cmd: 'echo "${{ needs.select-a-workflow.outputs.next_semver }}"'
                  enable_tag_v_prefix: ${{ inputs.enable_tag_v_prefix }}
                  github_api_url: ${{ inputs.github_api_url }}
                  github_server: ${{ inputs.github_server }}
        needs: select-a-workflow
