name: workflow-selector
run-name: ${{ github.actor }} is checking which workflow to run
on:
    workflow_call:
        inputs:
            committer_email:
                description: Git user email address to use when commiting the changelog.
                required: true
                type: string
            committer_gpg_key:
                description: Git user GPG key to use when commiting the changelog.
                default: ""
                required: false
                type: string
            committer_name:
                description: Git username to use when commiting the changelog.
                required: true
                type: string
            add_files_to_commit:
                default: ""
                description: |2
                  A text file (UTF-8) containing 1 file per line to add along with the
                  changelog commit. The path should be relative to the root of the
                  repository. Line endings can be Linux, Mac, or Windows.
                required: false
                type: string
        secrets:
            github_write_token:
                required: true
                description: Personal GitHub access token to allow GitHub API request to trigger workflows.

concurrency:
    group: qa-group
    cancel-in-progress: false

env:
    GH_WRITE_TOKEN: ${{ secrets.github_write_token }}

jobs:
    select-a-workflow:
        runs-on: ubuntu-latest
        name: Select which workflow to run
        outputs:
            workflow: ${{ steps.selector.outputs.workflow }}
            changelog_hash: ${{ steps.selector.outputs.changelog_hash }}
            next_semver: ${{ steps.selector.outputs.next_semver }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-tags: true
                  fetch-depth: 0
            - name: Select a workflow
              uses: kohirens/version-release/.github/actions/workflow-selector@VERSION_RELEASE_IMAGE
              id: selector
    publish-changelog:
        permissions:
            contents: write
        if: ${{ needs.select-a-workflow.outputs.workflow == 'publish-changelog' }}
        runs-on: ubuntu-latest
        name: Publish changelog workflow
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-tags: true
                  fetch-depth: 0
            - name: Update and publish the changelog
              uses: kohirens/version-release/.github/actions/publish-changelog@VERSION_RELEASE_IMAGE
              id: changelog
              with:
                  changelog_hash: ${{ needs.select-a-workflow.outputs.changelog_hash }}
                  committer_email: ${{ inputs.committer_email }}
                  committer_gpg_key: ${{ inputs.committer_gpg_key }}
                  committer_name: ${{ inputs.committer_name }}
                  add_files_to_commit: ${{ inputs.add_files_to_commit }}
        needs: select-a-workflow
    publish-release-tag:
        if: ${{ needs.select-a-workflow.outputs.workflow == 'publish-release-tag' }}
        runs-on: ubuntu-latest
        name: Publish release workflow
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-tags: true
                  fetch-depth: 0
            - name: Publish a release
              uses: kohirens/version-release/.github/actions/publish-release-tag@VERSION_RELEASE_IMAGE
              id: release
              with:
                  tag_cmd: 'echo "${{ needs.select-a-workflow.outputs.next_semver }}"'
        needs: select-a-workflow
